#pragma once

#define ACHIEVEMENT_RTFM @"64913"
#define ACHIEVEMENT_RTFM_NAME @"RTFM"
#define ACHIEVEMENT_RTFM_DESCRIPTION @"read the instructions"
#define ACHIEVEMENT_N00BS_FIRST_LOLCAT @"69443"
#define ACHIEVEMENT_N00BS_FIRST_LOLCAT_NAME @"n00b's first lolcat"
#define ACHIEVEMENT_N00BS_FIRST_LOLCAT_DESCRIPTION @"collect a lolcat"
#define ACHIEVEMENT_LOLLERSKATER_SOS @"69453"
#define ACHIEVEMENT_LOLLERSKATER_SOS_NAME @"lollerskater S.O.S."
#define ACHIEVEMENT_LOLLERSKATER_SOS_DESCRIPTION @"rescue your first lollerskater"
#define ACHIEVEMENT_I_CAN_HAS_CHEEZBURGER @"69463"
#define ACHIEVEMENT_I_CAN_HAS_CHEEZBURGER_NAME @"i can has cheezburger"
#define ACHIEVEMENT_I_CAN_HAS_CHEEZBURGER_DESCRIPTION @"feed a cheezburger to a lolcat"
#define ACHIEVEMENT_GOD_MODE @"69473"
#define ACHIEVEMENT_GOD_MODE_NAME @"god mode"
#define ACHIEVEMENT_GOD_MODE_DESCRIPTION @"play 4 minutes without dying"
#define ACHIEVEMENT_AVERAGE @"69483"
#define ACHIEVEMENT_AVERAGE_NAME @"<troll>average</troll>"
#define ACHIEVEMENT_AVERAGE_DESCRIPTION @"average trolls have entered the game"
#define ACHIEVEMENT_OMG_A_VIRUS_ @"69503"
#define ACHIEVEMENT_OMG_A_VIRUS__NAME @"omg a virus!"
#define ACHIEVEMENT_OMG_A_VIRUS__DESCRIPTION @"viruses have entered the game"
#define ACHIEVEMENT_RUTHLESS @"69513"
#define ACHIEVEMENT_RUTHLESS_NAME @"<troll>ruthless</troll>"
#define ACHIEVEMENT_RUTHLESS_DESCRIPTION @"ruthless trolls have entered the game"
#define ACHIEVEMENT_FLAMING_ @"69533"
#define ACHIEVEMENT_FLAMING__NAME @"<troll>FLAMING!</troll>"
#define ACHIEVEMENT_FLAMING__DESCRIPTION @"flaming trolls have entered the game"
#define ACHIEVEMENT_THE_OPEN_PORT @"69543"
#define ACHIEVEMENT_THE_OPEN_PORT_NAME @"the open port"
#define ACHIEVEMENT_THE_OPEN_PORT_DESCRIPTION @"firewalls have entered the game"
#define ACHIEVEMENT_CAT_LADY @"69553"
#define ACHIEVEMENT_CAT_LADY_NAME @"cat lady"
#define ACHIEVEMENT_CAT_LADY_DESCRIPTION @"collect 500 lolcats total"
#define ACHIEVEMENT_OVER_9000 @"69573"
#define ACHIEVEMENT_OVER_9000_NAME @"over 9000!!!"
#define ACHIEVEMENT_OVER_9000_DESCRIPTION @"get over 9000 score total"
#define ACHIEVEMENT_SOMEBODY_SET_US_UP_THE_BOMB @"69583"
#define ACHIEVEMENT_SOMEBODY_SET_US_UP_THE_BOMB_NAME @"somebody set us up the bomb"
#define ACHIEVEMENT_SOMEBODY_SET_US_UP_THE_BOMB_DESCRIPTION @"blow up 20 trolls in a game"
#define ACHIEVEMENT_RICKROLLD @"69593"
#define ACHIEVEMENT_RICKROLLD_NAME @"rickroll'd"
#define ACHIEVEMENT_RICKROLLD_DESCRIPTION @"get rickroll'd"
#define ACHIEVEMENT_KITTENS_INSPIRED_BY_KITTENS @"69603"
#define ACHIEVEMENT_KITTENS_INSPIRED_BY_KITTENS_NAME @"kittens inspired by kittens"
#define ACHIEVEMENT_KITTENS_INSPIRED_BY_KITTENS_DESCRIPTION @"collect 30 lolcats in a game"
#define ACHIEVEMENT_DONT_TAZE_ME_BRO @"69613"
#define ACHIEVEMENT_DONT_TAZE_ME_BRO_NAME @"don't taze me, bro"
#define ACHIEVEMENT_DONT_TAZE_ME_BRO_DESCRIPTION @"get killed by the firewall 3 times in a game"
#define ACHIEVEMENT_IS_THIS_GONNA_BE_FOREVER @"69623"
#define ACHIEVEMENT_IS_THIS_GONNA_BE_FOREVER_NAME @"is this gonna be forever?"
#define ACHIEVEMENT_IS_THIS_GONNA_BE_FOREVER_DESCRIPTION @"waste a total of 12 hours on teh internets"
#define ACHIEVEMENT_IMMA_LET_YOU_FINISH_ @"69633"
#define ACHIEVEMENT_IMMA_LET_YOU_FINISH__NAME @"imma let you finish!"
#define ACHIEVEMENT_IMMA_LET_YOU_FINISH__DESCRIPTION @"survive teh internets for 10 minutes"
#define ACHIEVEMENT_GODWINS_LAW @"69643"
#define ACHIEVEMENT_GODWINS_LAW_NAME @"godwin's law"
#define ACHIEVEMENT_GODWINS_LAW_DESCRIPTION @"feed trolls a total of 500 cheezburgers"
#define ACHIEVEMENT_DNFTT @"69653"
#define ACHIEVEMENT_DNFTT_NAME @"DNFTT!"
#define ACHIEVEMENT_DNFTT_DESCRIPTION @"make 400 score in a game without feeding any trolls"
#define ACHIEVEMENT_ITS_PEANUT_BUTTER_JELLY_TIME @"69663"
#define ACHIEVEMENT_ITS_PEANUT_BUTTER_JELLY_TIME_NAME @"it's peanut butter jelly time"
#define ACHIEVEMENT_ITS_PEANUT_BUTTER_JELLY_TIME_DESCRIPTION @"rescue a total of 20 lollerskaters"
#define ACHIEVEMENT_HAMMER_TIME @"69673"
#define ACHIEVEMENT_HAMMER_TIME_NAME @"hammer time"
#define ACHIEVEMENT_HAMMER_TIME_DESCRIPTION @"play with 7 game elements at once"
#define ACHIEVEMENT_THE_BACKDOOR @"69683"
#define ACHIEVEMENT_THE_BACKDOOR_NAME @"the backdoor"
#define ACHIEVEMENT_THE_BACKDOOR_DESCRIPTION @"pass safely through 10 firewalls in a game"

